// CommonJS lazy initialization pattern as generated by @rollup/plugin-commonjs
var fails;
var hasRequiredFails;
function requireFails() {
	if (hasRequiredFails) return fails;
	hasRequiredFails = 1;
	fails = function (exec) {
		try {
			exec();
			return false;
		} catch {
			return true;
		}
	};
	return fails;
}

assert.ok(
	requireFails()(function () {
		Object.getPrototypeOf(null);
	}),
	'lazily initialized helper: callback was not retained'
);

// Helper returned from another function call
const returnedHelper = (function () {
	const helper = exec => {
		try {
			exec();
			return false;
		} catch {
			return true;
		}
	};
	return helper;
})();

assert.ok(
	returnedHelper(() => {
		Object.getPrototypeOf(null);
	}),
	'helper returned from a function call: callback was not retained'
);

// Helper that is assigned to an already declared variable
var reassigned;
reassigned = exec => {
	try {
		exec();
		return false;
	} catch {
		return true;
	}
};

assert.ok(
	reassigned(() => {
		Object.getPrototypeOf(null);
	}),
	'reassigned helper: callback was not retained'
);

// Helper that is assigned via a logical assignment
var logicalAssignment;
logicalAssignment ??= exec => {
	try {
		exec();
		return false;
	} catch {
		return true;
	}
};

assert.ok(
	logicalAssignment(() => {
		Object.getPrototypeOf(null);
	}),
	'logically assigned helper: callback was not retained'
);

assert.ok(!requireFails()(() => {}), 'no false positive feature detection');
