/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parse(code: string, allowReturnOutsideFunction: boolean, jsx: boolean): Buffer

export declare function parseAsync(code: string, allowReturnOutsideFunction: boolean, jsx: boolean, signal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function parseAndWalk(code: string, allowReturnOutsideFunction: boolean, jsx: boolean, nodeBitsetBuffer: Uint8Array, signal?: AbortSignal | undefined | null): Promise<Buffer>

export declare function xxhashBase16(input: Uint8Array): string

export declare function xxhashBase36(input: Uint8Array): string

export declare function xxhashBase64Url(input: Uint8Array): string
