require('./bundle-information');
require('./fs-override');
require('./get-log-filter');
require('./parse-ast');
require('./iife');
require('./in-memory-sourcemaps');
require('./misc');
require('./sanity-checks');
require('./umd');
