require('./acorn-plugins');
require('./bundle-information');
require('./deprecations');
require('./iife');
require('./in-memory-sourcemaps');
require('./misc');
require('./queue');
require('./sanity-checks');
require('./umd');
