[build]
rustflags = "-C opt-level=z -Z location-detail=none -Z unstable-options -C panic=immediate-abort"

[unstable]
build-std = ["std", "core", "alloc", "panic_abort"]
build-std-features = ["optimize_for_size"]
