// This file is generated by scripts/generate-ast-to-buffer.ts.
// Do not edit this file directly.

import type { ast } from '../rollup/types';
import type { AstBufferForWriting } from './getAstBuffer';

export type NodeSerializer<T extends ast.AstNode> = (
	node: T,
	buffer: AstBufferForWriting
) => AstBufferForWriting;

export const serializeDirective: NodeSerializer<ast.Directive> = (node, buffer, position) => {
	buffer[position] = 21;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeExpressionStatement: NodeSerializer<ast.ExpressionStatement> = (
	node,
	buffer,
	position
) => {
	buffer[position] = 28;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralBigInt: NodeSerializer<ast.LiteralBigInt> = (
	node,
	buffer,
	position
) => {
	buffer[position] = 58;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralBoolean: NodeSerializer<ast.LiteralBoolean> = (
	node,
	buffer,
	position
) => {
	buffer[position] = 59;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralNull: NodeSerializer<ast.LiteralNull> = (node, buffer, position) => {
	buffer[position] = 60;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralNumber: NodeSerializer<ast.LiteralNumber> = (
	node,
	buffer,
	position
) => {
	buffer[position] = 61;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralRegExp: NodeSerializer<ast.LiteralRegExp> = (
	node,
	buffer,
	position
) => {
	buffer[position] = 62;
	buffer[position + 1] = node.start;
	buffer[position + 2] = node.end;
	return [buffer, position + 3];
};

export const serializeLiteralString: NodeSerializer<ast.LiteralString> = (node, buffer) => {
	const nodePosition = buffer.position;
	buffer.position = nodePosition + 4;
	buffer[nodePosition] = 63;
	buffer[nodePosition + 1] = node.start;
	buffer[nodePosition + 2] = node.end;
	buffer.addStringToBuffer(node.value, nodePosition + 3);
	return buffer;
};
