// This file is generated by scripts/generate-scope-constants.ts.
// Do not edit this file directly.

export const SCOPE_PARENT_OFFSET = 0;
export const SCOPE_DECLARATION_COUNT_OFFSET = 1;
export const SCOPE_DECLARATIONS_OFFSET = 2;
