import { ESLint } from 'eslint';
import { spawn } from 'node:child_process';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { blue, bold, cyan, green, magenta, red, yellow } from './colors.ts';

const colors = [cyan, yellow, blue, red, green, magenta];
let nextColorIndex = 0;

export function runWithEcho(
	command: string,
	parameters: string[],
	options?: Parameters<typeof spawn>[2]
): Promise<void> {
	const color = colors[nextColorIndex];
	nextColorIndex = (nextColorIndex + 1) % colors.length;
	return new Promise((resolve, reject) => {
		const commandString = formatCommand(command, parameters);
		console.error(bold(`\n${color('Run>')} ${commandString}`));

		const childProcess = spawn(command, parameters, { stdio: 'inherit', ...options });

		childProcess.on('close', code => {
			if (code) {
				reject(new Error(`"${commandString}" exited with code ${code}.`));
			} else {
				console.error(bold(`${color('Finished>')} ${commandString}\n`));
				resolve();
			}
		});
	});
}

export function runAndGetStdout(command: string, parameters: string[]): Promise<string> {
	return new Promise((resolve, reject) => {
		const childProcess = spawn(command, parameters);
		let stdout = '';

		childProcess.stderr.pipe(process.stderr);
		childProcess.stdout.on('data', data => (stdout += String(data)));

		childProcess.on('close', code => {
			if (code) {
				reject(new Error(`"${formatCommand(command, parameters)}" exited with code ${code}.`));
			} else {
				resolve(stdout.trim());
			}
		});
	});
}

function formatCommand(command: string, parameters: string[]): string {
	return [command, ...parameters].join(' ');
}

export async function readJson(file: string): Promise<Record<string, any>> {
	const content = await readFile(file, 'utf8');
	return JSON.parse(content);
}

export async function lintTsFile(file: URL): Promise<void> {
	const eslint = new ESLint({ fix: true });
	const results = await eslint.lintFiles([fileURLToPath(file)]);
	await ESLint.outputFixes(results);
	const formatter = await eslint.loadFormatter('stylish');
	const resultText = await formatter.format(results);
	if (resultText.trim().length > 0) {
		console.log(resultText);
	}
}

export function lintRustFile(file: URL): Promise<void> {
	return runWithEcho('rustfmt', [fileURLToPath(file)]);
}

// Lowercase the first letters while maintaining camel casing, e.g. "ASTNode" -> "astNode"
export function firstLettersLowercase(string: string): string {
	return string.replace(/^[A-Z]+/, match =>
		match.length === 1 ? match.toLowerCase() : match.slice(0, -1).toLowerCase() + match.slice(-1)
	);
}

export function toSnakeCase(string: string): string {
	return string.replace(/(?<!^)([A-Z])([a-z])/g, '_$1$2').toLowerCase();
}

export function toScreamingSnakeCase(string: string): string {
	return string.replace(/(?<!^)([A-Z])([a-z])/g, '_$1$2').toUpperCase();
}

export function generateNotEditFilesComment(filePath: string): string {
	return `// This file is generated by ${path.relative(process.cwd(), fileURLToPath(filePath)).replaceAll('\\', '/')}.
// Do not edit this file directly.\n\n`;
}
