name: Install and Cache Node Dependencies
description: Installs Node dependencies and saves cache if not already cached.
runs:
  using: composite
  steps:
    - name: Restore Node dependencies cache
      id: cache-node-modules
      uses: actions/cache/restore@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path:  |
          node_modules
          ~/.npm
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package-lock.json') }}
        restore-keys: node-modules-${{ runner.os }}-${{ runner.arch }}
    - name: Install Node dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ${{ github.ref == 'refs/heads/master' && 'ci' || 'install' }} --ignore-scripts && npm run prepare:patch
      shell: bash
    - name: Save Node dependencies cache
      if: steps.cache-node-modules.outputs.cache-hit != 'true' && github.ref == 'refs/heads/master'
      uses: actions/cache/save@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      with:
        path: |
          node_modules
          ~/.npm
        key: node-modules-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package-lock.json') }}

