// This file is generated by scripts/generate-ast-converters.js.
// Do not edit this file directly.

pub const TYPE_PARSE_ERROR: [u8; 4] = 0u32.to_ne_bytes();
pub const TYPE_ARRAY_EXPRESSION_SIMPLE: [u8; 4] = 1u32.to_ne_bytes();
pub const TYPE_ARRAY_PATTERN_SIMPLE: [u8; 4] = 2u32.to_ne_bytes();
pub const TYPE_ARROW_FUNCTION_EXPRESSION_FLAGS: [u8; 4] = 3u32.to_ne_bytes();
pub const TYPE_ASSIGNMENT_EXPRESSION: [u8; 4] = 4u32.to_ne_bytes();
pub const TYPE_ASSIGNMENT_PATTERN: [u8; 4] = 5u32.to_ne_bytes();
pub const TYPE_BREAK_STATEMENT: [u8; 4] = 6u32.to_ne_bytes();
pub const TYPE_PROGRAM: [u8; 4] = 7u32.to_ne_bytes();

pub const ARROW_FUNCTION_EXPRESSION_RESERVED_BYTES: usize = 20;
pub const ARROW_FUNCTION_EXPRESSION_ASYNC_FLAG: u32 = 1;
pub const ARROW_FUNCTION_EXPRESSION_EXPRESSION_FLAG: u32 = 2;
pub const ARROW_FUNCTION_EXPRESSION_GENERATOR_FLAG: u32 = 4;
pub const ARROW_FUNCTION_EXPRESSION_ANNOTATIONS_OFFSET: usize = 8;
pub const ARROW_FUNCTION_EXPRESSION_BODY_OFFSET: usize = 12;
pub const ARROW_FUNCTION_EXPRESSION_PARAMS_OFFSET: usize = 16;

pub const ASSIGNMENT_EXPRESSION_RESERVED_BYTES: usize = 16;
pub const ASSIGNMENT_EXPRESSION_LEFT_OFFSET: usize = 4;
pub const ASSIGNMENT_EXPRESSION_OPERATOR_OFFSET: usize = 8;
pub const ASSIGNMENT_EXPRESSION_RIGHT_OFFSET: usize = 12;

pub const ASSIGNMENT_PATTERN_RESERVED_BYTES: usize = 12;
pub const ASSIGNMENT_PATTERN_LEFT_OFFSET: usize = 4;
pub const ASSIGNMENT_PATTERN_RIGHT_OFFSET: usize = 8;

pub const BREAK_STATEMENT_RESERVED_BYTES: usize = 8;
pub const BREAK_STATEMENT_LABEL_OFFSET: usize = 4;

pub const PROGRAM_RESERVED_BYTES: usize = 12;
pub const PROGRAM_ANNOTATIONS_OFFSET: usize = 4;
pub const PROGRAM_BODY_OFFSET: usize = 8;
