// This file is generated by scripts/generate-scope-constants.ts.
// Do not edit this file directly.

pub const SCOPE_PARENT_OFFSET: usize = 0;
pub const SCOPE_DECLARATION_COUNT_OFFSET: usize = 4;
pub const SCOPE_DECLARATIONS_OFFSET: usize = 8;
