name: Prepare Build Artifacts
description: Downloads all artifacts, copies WASM files, builds JavaScript, and moves artifacts
runs:
  using: composite
  steps:
    - name: Download all artifacts
      uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
      with:
        path: artifacts
    - name: Copy WASM files
      shell: bash
      run: cp -R artifacts/bindings-wasm/wasm .
    - name: Build JavaScript
      shell: bash
      run: npm run build:cjs && cp artifacts/*/*.node dist/ && npm run build:bootstrap
    - name: Move artifacts
      shell: bash
      run: npm run ci:artifacts

