name: Build REPL artefacts

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: >-
      ${{ github.event.pull_request.head.repo.full_name == 'rollup/rollup' ||
          (github.event.action == 'labeled' && github.event.label.name == 'x⁸ ⚙️ build repl artefacts') }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          toolchain: nightly-2025-07-25
          components: rust-src
      - name: Restore Cargo cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            rust/target/
          key: wasm-cargo-ubuntu-latest-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: wasm-cargo-ubuntu-latest
      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.10.0
      - name: Install and Cache Node Dependencies
        uses: ./.github/actions/install-and-cache-node-deps
      - name: Build artefacts
        run: >-
          npm exec -- concurrently -c green,blue,yellow 'npm:build:napi -- --release' 'npm run build:wasm' 'npm:build:cjs' &&
          npm run build:copy-native && npm run build:bootstrap
      - name: Upload artefacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: repl-artefacts
          path: |
            browser/dist/rollup.browser.js
            browser/dist/rollup.browser.js.map
            browser/dist/bindings_wasm_bg.wasm
          if-no-files-found: error
          retention-days: 1
