name: Build REPL artefacts

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    if: >-
      ${{ github.event.pull_request.head.repo.full_name == 'rollup/rollup' ||
          (github.event.action == 'labeled' && github.event.label.name == 'x⁸ ⚙️ build repl artefacts') }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Commit
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable
        with:
          toolchain: nightly-2025-07-25
          components: rust-src
      - name: Restore Cargo cache
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            rust/target/
          key: wasm-cargo-ubuntu-latest-${{ hashFiles('rust/Cargo.lock') }}
          restore-keys: wasm-cargo-ubuntu-latest
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.10.0
      - name: Install and Cache Node Dependencies
        uses: ./.github/actions/install-and-cache-node-deps
      - name: Build artefacts
        run: >-
          npm exec -- concurrently -c green,blue,yellow 'npm:build:napi -- --release' 'npm run build:wasm' 'npm:build:cjs' &&
          npm run build:copy-native && npm run build:bootstrap
      - name: Upload artefacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: repl-artefacts
          path: |
            browser/dist/rollup.browser.js
            browser/dist/rollup.browser.js.map
            browser/dist/bindings_wasm_bg.wasm
          if-no-files-found: error
          retention-days: 1
